const $ = (id) => document.getElementById(id);
const state = $("serviceState");
function setState(kind, text) { state.className = `service-state ${kind}`; state.lastElementChild.textContent = text; document.body.dataset.serviceState = kind; }
async function api(path, options = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 5000); try { const response = await fetch(path, {...options, signal: controller.signal}); const data = await response.json(); if (!response.ok) throw new Error(data.message || "This service is temporarily unavailable."); return data; } finally { clearTimeout(timer); } }
function message(error) { return error.name === "AbortError" ? "The request timed out. Please try again in a few minutes." : error.message; }
async function loadRegions() { try { const data = await api("/api/regions"); $("regionList").innerHTML = data.regions.map(r => `<div><strong>${r.name}</strong><span>${r.state}</span></div>`).join(""); setState("ok", "Bulletin service available"); } catch (error) { $("regionList").innerHTML = `<div>We couldn't load current supply information.</div>`; setState("error", "Bulletin service unavailable"); } }
async function findSchedule() { const button=$("findSchedule"), result=$("scheduleResult"), region=$("regionSelect").value; button.disabled=true; button.textContent="Finding schedule"; result.className="schedule-result"; result.textContent=""; try { const data=await api(`/api/schedules?region=${encodeURIComponent(region)}`); const row=data.schedules[0]; result.textContent=row ? `${row.region}: ${row.window}, ${row.status}.` : "No scheduled delivery window was found."; } catch(error) { result.classList.add("error"); result.textContent=message(error); } finally { button.disabled=false; button.textContent="View delivery schedule"; } }
async function subscribe() { const messageBox=$("subscribeMessage"); messageBox.className="subscribe-message"; messageBox.textContent="Saving your subscription…"; try { const data=await api("/api/subscriptions",{method:"POST"}); messageBox.classList.add("success"); messageBox.textContent=data.message; } catch(error) { messageBox.classList.add("error"); messageBox.textContent=message(error); } }
$("findSchedule").addEventListener("click",findSchedule); $("subscribe").addEventListener("click",subscribe); $("subscribeTop").addEventListener("click",subscribe); loadRegions();
