const $ = (id) => document.getElementById(id);
const state = $("serviceState");
const cart = [];
const setState = (kind, text) => { state.className = `service-state ${kind}`; state.lastElementChild.textContent = text; document.body.dataset.serviceState = kind; };
async function api(path, options = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 5000); try { const r = await fetch(path, {...options, signal: controller.signal}); const data = await r.json(); if (!r.ok) throw new Error(data.message || "The service is temporarily unavailable."); return data; } finally { clearTimeout(timer); } }
function errorMessage(error) { return error.name === "AbortError" ? "The request timed out. Please try again in a few minutes." : error.message; }
async function loadCircuits() { try { const data = await api("/api/circuits"); $("circuitRows").innerHTML = data.circuits.map(c => `<tr><td>${c.location}</td><td>${c.id}</td><td>${c.service}</td><td><span class="status ${c.state === "Operational" ? "ok" : "review"}">${c.state}</span></td><td>${c.checked}</td></tr>`).join(""); setState("ok", "Service available"); } catch (error) { $("circuitRows").innerHTML = `<tr><td colspan="5">We couldn't load circuit status. ${errorMessage(error)}</td></tr>`; setState("error", "Service unavailable"); } }
async function runDiagnostic() { const button = $("diagnose"), result = $("diagnosticResult"); button.disabled = true; button.textContent = "Checking field link"; result.hidden = true; try { const data = await api("/api/diagnostics"); result.className = "result"; result.textContent = `Field link confirmed. Last response ${data.checked_at}.`; } catch (error) { result.className = "result error"; result.textContent = errorMessage(error); } finally { result.hidden = false; button.disabled = false; button.textContent = "Check live link"; } }
async function createCase() { const button = $("createCase"), message = $("caseMessage"); button.disabled = true; message.className = "action-message"; message.textContent = "Sending your field note…"; try { const data = await api("/api/cases", {method:"POST"}); message.className = "action-message success"; message.textContent = `Field case ${data.case} is open. The route desk has your note.`; } catch (error) { message.className = "action-message error"; message.textContent = errorMessage(error); } finally { button.disabled = false; } }
$("diagnose").addEventListener("click", runDiagnostic); $("createCase").addEventListener("click", createCase); loadCircuits();
function renderCart(){const total=cart.reduce((sum,item)=>sum+item.price,0);$("cartCount").textContent=cart.length;$("cartItems").innerHTML=cart.length?cart.map(item=>`<li><span>${item.name}</span><b>$${item.price}</b></li>`).join(""):"<li>Your bag is empty.</li>";$("cartTotal").textContent=`$${total}`}
function openCart(open){$("cartDrawer").classList.toggle("open",open);$("cartDrawer").setAttribute("aria-hidden",String(!open))}
document.querySelectorAll(".add-cart").forEach(button=>button.addEventListener("click",()=>{cart.push({name:button.dataset.product,price:Number(button.dataset.price)});renderCart();openCart(true)}));
$("cartButton").addEventListener("click",()=>openCart(true));$("cartClose").addEventListener("click",()=>openCart(false));$("checkout").addEventListener("click",async()=>{const button=$("checkout"),message=$("cartMessage"),drawer=$("cartDrawer");if(!cart.length){message.textContent="Add something to your field bag first.";return}drawer.classList.remove("outage");drawer.classList.add("checking");button.disabled=true;button.textContent="Contacting checkout…";try{await api("/api/diagnostics");const total=$("cartTotal").textContent;message.textContent=`Order NL-${String(Date.now()).slice(-6)} confirmed. Your ${total} field kit is being prepared.`;cart.splice(0);renderCart();button.textContent="Order confirmed"}catch(error){await new Promise(resolve=>setTimeout(resolve,1400));drawer.classList.remove("checking");drawer.classList.add("outage");message.innerHTML=`<span class="outage-code">CHECKOUT / PUBLIC PATH UNAVAILABLE</span><strong>We could not create your order.</strong><span>Your field bag is saved, but the public checkout route returned a service-unavailable response.</span><small>${errorMessage(error)}</small>`;button.textContent="Retry checkout"}finally{drawer.classList.remove("checking");button.disabled=false}});renderCart();
const stage=$("productStack").parentElement;stage.addEventListener("pointermove",event=>{const box=stage.getBoundingClientRect();stage.style.setProperty("--mx",`${(event.clientX-box.left)/box.width*100}%`);stage.style.setProperty("--my",`${(event.clientY-box.top)/box.height*100}%`)});
