const $ = (id) => document.getElementById(id);
const state = $("serviceState");
const setState = (kind, text) => { state.className = `service-state ${kind}`; state.lastElementChild.textContent = text; document.body.dataset.serviceState = kind; };
async function api(path, options = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 5000); try { const r = await fetch(path, {...options, signal: controller.signal}); const data = await r.json(); if (!r.ok) throw new Error(data.message || "The service is temporarily unavailable."); return data; } finally { clearTimeout(timer); } }
function errorMessage(error) { return error.name === "AbortError" ? "The request timed out. Please try again in a few minutes." : error.message; }
async function loadCircuits() { try { const data = await api("/api/circuits"); $("circuitRows").innerHTML = data.circuits.map(c => `<tr><td>${c.location}</td><td>${c.id}</td><td>${c.service}</td><td><span class="status ${c.state === "Operational" ? "ok" : "review"}">${c.state}</span></td><td>${c.checked}</td></tr>`).join(""); setState("ok", "Service available"); } catch (error) { $("circuitRows").innerHTML = `<tr><td colspan="5">We couldn't load circuit status. ${errorMessage(error)}</td></tr>`; setState("error", "Service unavailable"); } }
async function runDiagnostic() { const button = $("diagnose"), result = $("diagnosticResult"); button.disabled = true; button.textContent = "Checking connection"; result.hidden = true; try { const data = await api("/api/diagnostics"); result.className = "result"; result.textContent = `${data.summary} Checked ${data.checked_at}.`; } catch (error) { result.className = "result error"; result.textContent = errorMessage(error); } finally { result.hidden = false; button.disabled = false; button.textContent = "Run connection check"; } }
async function createCase() { const button = $("createCase"), message = $("caseMessage"); button.disabled = true; message.className = "action-message"; message.textContent = "Creating your service case…"; try { const data = await api("/api/cases", {method:"POST"}); message.className = "action-message success"; message.textContent = `${data.case} is open. ${data.message}`; } catch (error) { message.className = "action-message error"; message.textContent = errorMessage(error); } finally { button.disabled = false; } }
$("diagnose").addEventListener("click", runDiagnostic); $("createCase").addEventListener("click", createCase); loadCircuits();
